version: '3.8'

services:
  backend:
    build: ./server
    image: hackner/backend:latest
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    build: ./client
    image: hackner/frontend:latest
    ports:
      - '80:80'
    networks:
      - app-network

  mongodb:
    image: 'mongo:4.4'
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
