name: Backend Python CI Testing

on:
  push:
    branches: [ "merged-branches" ]
  pull_request:
    branches: [ "merged-branches" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install testing tools
      run: |
        pip install pytest pylint

    - name: Run PyLint
      working-directory: server
      run: |
        pylint --exit-zero **/*.py

    - name: Run PyTest
      working-directory: server
      env:
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        pytest
