name: Docker

on:
  push:
    branches:
      - merged-branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml --verbose build
        docker-compose -f docker-compose.yml --verbose push
