name: Frontend Docker Image CI

on:
  push:
    branches: [ "merged-branches" ]
  pull_request:
    branches: [ "merged-branches" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: your-docker-hub-username/frontend:latest