name: Python Application

on:
  push:
    branches:
      - merged-branches
  pull_request:
    branches:
      - merged-branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      uses: pavelzw/pytest-action@v2.1.0
      with:
        job-summary: false
        verbose: true
        emoji: false
        custom-arguments: ""
        custom-pytest: "python -m pytest server"
        report-title: "Test Report"
        click-to-expand: true
